### ISSUE TITLE
ページの URL の形の議論

### ISSUE THREAD

**Issue by KashEight** [lc-tut/club-portal#2]
# 何がしたいの

特定のサークルの情報を得るために URL としてアクセスする必要があるがどのような形にするか決めたい.
例として言うと, 当サークルの名称は LinuxClub なので `http://example.jp/clubs/linux-club` や `http://example.jp/clubs/linuxclub` というような形が URL として考えられる.

(3/29 18:06 追記) 
今回の議論では, いわゆるフロントエンドに近い部分でブラウザの URL にどう表示されるかみたいな形の議論をする感じを目的としている感じです, 色々説明不足で申し訳ないです…
また足りなかったら追記するかもです.

(3/30 17:51 追記)
一応, 現状案として 10~20 文字の乱数文字を生成してそれを URL にする感じで進めようかと思います.
DB のプライマリキーに関しては, UUID (上記の乱数文字とは違う形) にする感じにします.
また, 自分はこの方法いいと思います！みたいなあれば言ってほしいのでこの Issue はオープンのままにしておきます.

# 提案
### 説明
`/clubs/1`, `/clubs/2`... といった感じに URL を決めていく.
この数字 ID は DB の都合上追加された順番となる

### メリット
- URL がとにかく短くなるので共有しやすい
- URL が衝突しない
- 順番がわかりやすい (ここは微妙かも)

### デメリット
- 追加した順番がわかりやすいのでサークル同士の不公平感が否めない
- サークルが消滅すると DB と URL に空き番が生じるので気持ち悪さが残る

### 説明
UUID (ここでは説明を省きます) を用いて URL を決めていく.
URL 例は `/clubs/b99d93b4-9672-463f-af4b-31f43bb30bb1` と言った感じ (`-` は抜くかもしれない)

### メリット
- URL が衝突する可能性が極端に低い
- 実装が楽 (kash / Hytus 個人の感想です)
- バックエンドの api としてすぐ使いやすい

### デメリット
- URL がとにかく長いのでそこが気持ち悪いし共有もしにくい
- URL だけではサークルがすぐにはわからない

### 説明
一番最初の例に出したような `clubs/linux-club` のような URL を決める.
URL に使う名称はサークル側が決め LinuxClub はほぼ関与しない.

### メリット
- サークルがすぐわかる
- 共有がしやすい
- LinuxClub に URL の決定権がほぼないため, こちらの負担が少ない

### デメリット
- 決めるサークル側が名称に日本語使ったりいたずらしたりするとこちらが非常に困ることがある
- バックエンドとの扱いが難しいかも

### 説明
基本的なことは案 3-1 と同様だが URL の決定は LinuxClub が全て決める.

### メリット
- サークルがすぐわかる
- 共有がしやすい
- サークルもろもろの問題の防止ができる

### デメリット
- URL の決定及び追加の作業があるので, 負担が多いのと負の遺産になる可能性
- バックエンドとの扱いが難しいかも

### 説明
UUID 方式と名前方式を同時に利用する.
例として, `/clubs/b99d93b4-9672-463f-af4b-31f43bb30bb1` と `/clubs/linux-club` 両方とも使う感じ.

### メリット
- バックエンドの api として連携しやすいかも
- サークルがすぐわかる
- 共有がしやすい

### デメリット
- 実装がかなりめんどいと思う (両方とも実装しなきゃいけんので)
- 案 3 のどちら側を利用するかを先に決めなきゃいけない

# 意見/新しい案等
あったら Slack, Discord, この Issue で言ってくれればありがたいです. (というより開発進まないので言って欲しい)

**Comment by KashEight** [comment]
参考: https://cloud.google.com/blog/products/api-management/api-design-choosing-between-names-and-identifiers-in-urls
Google がどのように api を決めてるか (今回の事例と似た感じ)

**Comment by tomoyk** [comment]
データベースで個々のエントリーを識別するために使うキー（識別子）と、URLで使う識別子は必ずしも一致する必要はないかなって思いました。

**Comment by kaoru-nk** [comment]
10文字くらいの乱数文字をidにするのはどうでしょうか
組み合わせは大文字小文字数字を入れれば62^10通りでサークルの数的に衝突可能性はほぼないと思われます

**Comment by KashEight** [comment]
さっそく意見ありがとうございます！

> データベースで個々のエントリーを識別するために使うキー（識別子）と、URLで使う識別子は必ずしも一致する必要はないかなって思いました。
> ツイッターはアカウント名（スクリーンネーム）をURLに含めていますが、実際には内部で別のIDをアカウントに割り当てていますね。

自分もそこは思っていて, 実際にそういうのを案 3 で提案したんですけど, 問題としてはそれで URL を作るとなると ID をどうやって作るべきかという問題が出てくるんですよね.

Twitter のようなサービスだと不特定多数の人間の中の一つといった感じなので例えばランダムな文字列のスクリーンネームも許容される感じなんですが, 今回の場合だと大学のサークルという特定の集団の一つと言ったところなので特定がしにくいランダム文字列それ自体が容認できるかと言ったところなんですよね. (これは案 2 でも言えることだと思います) 
そして, ランダム文字列を無視して自由に設定したとしても, うちみたいな "LinuxClub" という名称をもっているならまだしも, 体育会系の部活にあるような, "xxx部" とかの部活となると ID をどう設定するかみたいな問題もあると思います.

> あと、APIであればブラウザやスマホアプリが参照するので、URLの可読性はあまり意識する必要はない気がしました。

これは自分の書き方が悪かったんですが, フロントエンド部分, つまり見える範囲 (ここの Issue である https://github.com/lc-tut/club-portal/issues/2 の org 名の `lc-tut` やリポジトリ名の `club-portal` など) のことを今回自分が話したい部分ですね.
API の部分は見えない部分なので関係ない感じです.

**Comment by KashEight** [comment]
@kaoru-nk 

> 10文字くらいの乱数文字をidにするのはどうでしょうか
> 組み合わせは大文字小文字数字を入れれば62^10通りでサークルの数的に衝突可能性はほぼないと思われます

多分案として近いのは案 2 って感じですね, 確かにそれだと共有もしやすいですし, 内部で別 ID (おそらく UUID) に変換すればいい感じですからね.

**Comment by kaoru-nk** [comment]
裏はRDBMSを使うと思うんですが、それらは基本的にカラムごとにオートインクリメントなidを持っていると思うので、それを使うのが良いかと思います

**Comment by KashEight** [comment]
> 裏はRDBMSを使うと思うんですが、それらは基本的にカラムごとにオートインクリメントなidを持っていると思うので、それを使うのが良いかと思います

個人的には, カラム (特にプライマリキー) には UUID 使うつもりだったんですよね…
というのも, オートインクリメントの id の場合はサークルが消えたときにその番号が欠番になってしまうはずだったので. (勘違いだったら申し訳ないです)

**Comment by tomoyk** [comment]
> 自分もそこは思っていて, 実際にそういうのを案 3 で提案したんですけど, 問題としてはそれで URL を作るとなると ID をどうやって作るべきかという問題が出てくるんですよね.

前提が分からないので何とも言えないんですが、英数字である必要はあるんですかね？
例えば日本語をURLに含めて、URLエンコードしてもいいかなって思いました。ブラウザで表示する分にはURLが日本語で表示されますね。URLを直接入力しなければ問題ないかなって気がします。

URLを半角英数字にするのであれば、ユーザに入力してもらうか、APIやライブラリでふりがなを取り出すかあたりかなと思います。

**Comment by tomoyk** [comment]
これ結構いいかも。

https://qiita.com/NagaokaKenichi/items/6298eb8960570c7ad2e9

**Comment by KashEight** [comment]
>前提が分からないので何とも言えないんですが、英数字である必要はあるんですかね？
例えば日本語をURLに含めて、URLエンコードしてもいいかなって思いました。ブラウザで表示する分にはURLが日本語で表示されますね。ユーザがURLを直接入力しなければ問題ないかなって気がします。

例えば, ブラウザから `http://example.com/clubs/linuxclub` と `http://example.com/clubs/リナックスクラブ` でコピペした URL 比べてみたときに,

- 前者: `http://example.com/clubs/linuxclub` 
- 後者: `http://example.com/clubs/%E3%83%AA%E3%83%8A%E3%83%83%E3%82%AF%E3%82%B9%E3%82%AF%E3%83%A9%E3%83%96`

との違いがあって Twitter とかで URL を共有する際に前者と後者を比べるとやっぱり前者の方がわかりやすいなあという個人的な思いがある感じですね. そこは好みになっちゃうんですが…

> URLを半角英数字にするのであれば、ユーザに入力してもらうか、APIやライブラリでふりがなを取り出すかあたりかなと思います。

半角英数字にするとしたら現実的はユーザ入力なんですけど, アルファベット系の固有名称を持ってないサークル (特に部活系) のところが作るとなると他のところより URL がダサくなる (悪い言い方ですけれども) 問題があるんですよね.
例えば (存在しないですが) ゴルフ部だと, `http://example.com/clubs/gorufu-bu` とか `http://example.com/clubs/golfclub` といった URL になってしまうので他のサークルに対してイメージダウンするだろうなという感じがします.

なので, 現実の落とし所としては Qiita の記事 ID や @kaoru-nk さんの案がよさそうですね.

**Comment by KashEight** [comment]
DB の連番に関しては, 

- https://siguniang.wordpress.com/2013/03/17/stop-using-numbers-as-ids-just-use-uuids/
- https://zenn.dev/j5ik2o/articles/a085ab3e3d0f197f6559

に近い記事を以前に見たりや, 別大学のサークルが作ってるシステムが UUID をプライマリキーにしていたのを見たりしたので UUID を選ぼうと思った感じですね.
自分自身は DB あんまり詳しくないのもありベストプラクティスは流石にわからないのでこういうよくないかどうかはわからないのが本音です.

**Comment by KashEight** [comment]
> DB の連番に関しては,
> 
> * https://siguniang.wordpress.com/2013/03/17/stop-using-numbers-as-ids-just-use-uuids/
> * https://zenn.dev/j5ik2o/articles/a085ab3e3d0f197f6559
> 
> に近い記事を以前に見たりや, 別大学のサークルが作ってるシステムが UUID をプライマリキーにしていたのを見たりしたので UUID を選ぼうと思った感じですね.
> 自分自身は DB あんまり詳しくないのもありベストプラクティスは流石にわからないのでこういうのがよくないかどうかはわからないのが本音です.

**Comment by tomoyk** [comment]
データベースでよく使うのは，整数型のカラム idをつくり主キーとして、AUTO_INCREMENTを設定するケースですね。

レコードを追加するときに、idが最終レコードから加算されて、追加されます。また、主キーなので重複は排除された状態が作れます。

UUIDを使う場合は、サーバサイドでUUIDを生成して、データベース作成した文字列型のカラム uuid（主キー）に保存する感じですかね。

どちらでもいい感じだとは思いますよ。
長さの違いくらいな気もしました🍀

**Comment by tomoyk** [comment]
巨大なスケールになると整数型が枯渇する恐れがあるらしく、uuidを使ったほうがよいらしいです。今回は不要かもですが。。

https://yakst.com/ja/posts/4071

**Comment by KashEight** [comment]
なるほど…
個人的には UUID の方が扱いやすいという偏見みたいなのありますので今回は UUID 使う感じにしますか…
色々とありがとうございます 🙇

**Comment by KashEight** [comment]
URL に関してなんですが, UUID を SHA256 にかけたあと算出されたハッシュの 15 文字までを slug として扱うようにしました.
