### ISSUE TITLE
サークルページに必要な情報 (+DB 設計)

### ISSUE THREAD

**Issue by KashEight** [lc-tut/club-portal#3]
# 何がしたいの
サークルページに必要な情報は何かを色々考えたい.
ついでに DB 設計もできれば.

# 現状
## サークルページ自体
- サークル名
  - **必須**
- キャンパス
  - **必須**
  - 0: 蒲田, 1: 八王子
- タイプ (体育会系とか)
  - **必須**
  - 0: 体育会系, 1: 文化会系, 2: 実行委員会
- サークルの説明
  - **必須**
- 活動内容
  - 箇条書き
  - **必須**
- リンクとメールアドレス
  - Twitter, Instagram 等, 複数個あり
  - メールアドレスは**必須**
- 年間予定
  - 1 月 ~ 12 月まで + 備考
  - **必須**
- 活動実績等
  - 箇条書き
- 活動時間
  - 任意の曜日 + 備考
  - **必須**
- 活動場所
  - 箇条書き, 複数個あり
  - **必須**
- 画像
  - 複数個あり
- 動画
  - 複数個あり 

### サークルページ自体
- UUID (36 文字)
- URL (15 文字)
- サークル名 (最大 63 文字)
- 説明文 (最大 65535 文字)
- キャンパス (0: 蒲田, 1: 八王子 のどれか)
- サークルタイプ (0: 体育会系, 1: 文化会系, 2: 実行委員会)
- 公開しているか？ (bool, 0: 非公開, 1: 公開)
- 更新日 (datetime)

(加筆予定)

# ER 図
## 概要図

![club-portal-ER9](https://user-images.githubusercontent.com/18034370/115131592-2554f380-a034-11eb-942a-2671b7da42c2.png)

## DB

![club-portal-ER-DB9](https://user-images.githubusercontent.com/18034370/115131588-1c642200-a034-11eb-9560-066f7a26ca54.png)

**Comment by KashEight** [comment]
個人的に, サークルの説明と活動内容が被りがちなのとあいまいにしてた部分もいろいろあるのでもろもろを明確にやりたい

**Comment by tomoyk** [comment]
ER図を書くといい感じだと思いますよん

**Comment by KashEight** [comment]
一応 ER 図追加しました, 問題なかったら実装の方の ER 図も作って実際に実装しようかと思います.

**Comment by KashEight** [comment]
ER 図, すこし修正しました.

**Comment by KashEight** [comment]
DB 設計の方の ER 図を追加しました. 未完成な部分もありますが, 後に修正します.

**Comment by KashEight** [comment]
ふと思ったけれども, 活動場所と活動時間をセットにした方がいい気がしてきた… (そっちの方がわかりやすいかも)
また修正します.

**Comment by tomoyk** [comment]
活動詳細の「場所」は正規化しなくて良い気がしましたが，どうでしょう..?
場所で絞り込みをしたいニーズはある..? フロントである程度のバリデーションや選択肢を出せば良い気がしました．

**Comment by tomoyk** [comment]
SNSは種類(YouTube, LINE, ...)が多いので，カラム設計でゆるっとしても良いかなと思いました．
フロント側でカバーするか，サーバサイドでカバーするか悩ましいなぁ

```
+++ Links +++
- uuid (FK) →サークルと対応
- link_id (PK) →個別のリンクを一意識別(cf. link_labelとlink_urlの2つをまとめてPK)
- link_label →リンクの表示名(例: Twitter)
- link_url →リンク先のURL(例: https://twitter.com/lc_tut)
```

**Comment by tomoyk** [comment]
活動内容は，サークルページの中に1カラム作って，全部入れてしまって良い気がしました．

**Comment by KashEight** [comment]
>活動詳細の「場所」は正規化しなくて良い気がしましたが，どうでしょう..?
場所で絞り込みをしたいニーズはある..? フロントである程度のバリデーションや選択肢を出せば良い気がしました

これに関しては不定期開催があるサークルが一部ありまして, 時間があいまいでかつ場所もばらばらというどちらともに備考をつけないとどうしようもないという点から Many to Many の関連付けを行った感じです.
あとは, 体育会系のサークルや部が顕著なんですけど, 朝はある場所, 夕方は別の場所で行うサークルとかがあるからとかですかね…

> SNSは種類(YouTube, LINE, Facebook, ...)が多いので，カラム設計でゆるっとしても良いかなと思いました．
フロント側でカバーするか，サーバサイドでカバーするか悩ましいなぁ

SNS の種類に関する設計は確かにそうですね…頭からすっぽり抜けていました.
個人的には, 例としてあげられたテーブル設計はかなりいいと思います.
あと, テーブルの `link_label` は PK よりかは UNIQUE の方がいいかなあと思いました. (PK だと index きいて遅くなる気が)
カバーはサーバサイド側で任せるのがいいかと思います (フロントエンドは TypeScript の型定義である程度対応できるかと)

> 活動内容は，サークルページの中に1カラム作って，全部入れてしまって良い気がしました．

これは, 一番最初 (学務課から依頼されたとき) にまあまあ曖昧に決めてしまったのが原因で, 活動内容を箇条書きで書くか文章で書くか微妙にしてしまいました.
なので, この際活動内容は箇条書きとして統一させようと思って One to Many の関連付けをした感じですね…

**Comment by KashEight** [comment]
思ったけど, 画像ID とかそうなんですけど使わないなら PK を UUID にしてよかったですねこれ…なんか勘違いしてました

**Comment by tomoyk** [comment]
> これに関しては不定期開催があるサークルが一部ありまして, 時間があいまいでかつ場所もばらばらというどちらともに備考をつけないとどうしようもないという点から Many to Many の関連付けを行った感じです.

これ結構，つらそうですね〜．完全に理解しました．
同じ曜日の朝と夕をネストさせて持つなら，Many-to-Manyの設計の方がいいですね．

場所を正規化しなければ，こんな感じでもいいかなってイメージでした．JOINするとクエリ長くなるのと，活動場所からサークルを探すクエリ無いかなって気がして，これもありかなって思っていました．
これだと同じ曜日と活動場所を綺麗に扱うにはイマイチなので，どちらでも良いと思います！

```
+++  活動時間 +++
+ 活動時間ID -> PK
+ UUID -> FK
+ 曜日(int)
+ 時間(string)
+ 場所(string)
+ 備考(string)
```

**Comment by tomoyk** [comment]
>  カバーはサーバサイド側で任せるのがいいかと思います (フロントエンドは TypeScript の型定義である程度対応できるかと)

それでいいと思います．型っていいですよねー！（ぇ

**Comment by tomoyk** [comment]
> これは, 一番最初 (学務課から依頼されたとき) にまあまあ曖昧に決めてしまったのが原因で, 活動内容を箇条書きで書くか文章で書くか微妙にしてしまいました.

個人的にWYSIWYGのように書くイメージだったので，こう表現していました．
最初から箇条書きで決まっているなら，これでいいと思いました！

**Comment by KashEight** [comment]
最終的には学務課その他とまた相談して設計が変わるかもしれませんが, けっこういい感じに決まったと思うので, これで実装してみます！

色々とありがとうございました！😊

**Comment by KashEight** [comment]
実装して思ったんですけど, `ClubPage` (ER 図では `ClubSite` になってた…) から `ClubTime` に One to One の関連付けするよりも, 中間テーブルである `ActivityDetail` に UUID の FK 加えて関連付けした方が良い感じがしてきた…
結局, `ClubPage` からは `ClubTime` 及び `ClubPlace` も読むので両方に紐づいている `ActivityDetail` から JOIN する感じが一番よさげかな？

**Comment by KashEight** [comment]
実装中に気づきましたが, カラムが not null じゃないテーブル, 普通に良くなかったので実装の中で全て not null に変えました.
データベースだと値がない意味で NULL 使うべきじゃないですね…

ER 図は明日直します (今日は実装で浪費しましたので)

**Comment by tomoyk** [comment]
「活動時間」のUUIDは必要ない？

PKのカラム名に `hoge_pk` みたいなsuffixやprefixをつけるのを見たことがありますが，お好みでどうぞ．
UUIDというカラム名も意味が通る名前に変えたほうがいいかもですね．
今の`club_id` を `club_slug` にして， `uuid`  を `club_id` とかにするとか思いつきました．

**Comment by KashEight** [comment]
> 「活動時間」のUUIDは必要ない？

そうですね… まだ ER 図は修正してなかったのでそのままですけど実装では修正しております.

https://github.com/lc-tut/club-portal/blob/c68f6267c0e1380706db361acf0c31b8432a2942/models/detail.go#L3-L9

> PKのカラム名に `hoge_pk` みたいなsuffixやprefixをつけるのを見たことがありますが，お好みでどうぞ．
> UUIDというカラム名も意味が通る名前に変えたほうがいいかもですね．
> 今の`club_id` を `club_slug` にして， `uuid` を `club_id` とかにするとか思いつきました．

確かに, UUID のままだとわかりづらいですね…
PK のカラム名に関しては DB の管理の 7, 8 割ぐらいを ORM に任せてるのと, ER 図である程度わかるかなあと思います.

**Comment by tomoyk** [comment]
> そうですね… まだ ER 図は修正してなかったのでそのままですけど実装では修正しております.

👍 ばっちり

>  uuid に関しては UUID であることは少なくとも示したいので club_uuid に変更しようかなと思います.

他のID(例: video_id)が整数で定義されているので，区別しやすさという点でも `club_uuid` でいいと思います 💯 

---

ClubPlaceテーブルで気になったんですが，実際にサークルの活動場所を入力するのはユーザ（各サークルの担当者）ですかね？
活動場所をフリーテキストにして，ユーザに入力してもらうとすれば，正規化したメリットが薄いかなと思いました．
以下のように活動場所が同一の場合にフロント側で，自由入力にすると場所は同一でもレコードが分かれるかなぁと．

```
月 18:00-20:00 講義実験棟301
火 19:00-21:00 講義実験棟301
```

場所を登録する手順を挟んでから，活動場所を選択肢（place_id）から選ぶようなフロントの実装であれば，上記の話はないので忘れてください〜 🚀

**Comment by KashEight** [comment]
>ClubPlaceテーブルで気になったんですが，実際にサークルの活動場所を入力するのはユーザ（各サークルの担当者）ですかね？

そうですねー. 各サークルの担当者が入力する感じで設計しようと考えています.

>活動場所をフリーテキストにして，ユーザに入力してもらうとすれば，正規化したメリットが薄いかなと思いました

確かに, フリーテキストだとそこらへんのメリット薄いですね. 当初フリーテキストにしようと考えてた感じです.
なので, あげられている

> 場所を登録する手順を挟んでから，活動場所を選択肢（place_id）から選ぶようなフロントの実装

のような感じでフロント側に任せようかなと思います.
サークルによっては表記ゆれ問題 (講義実験棟と講実の違いなど) も発生する可能性あるのでそちらの方がいいですね.
具体的には, 曜日, 時間, 場所, それぞれ分けて書かせるような感じにしようかと思います.
~~実は PK と UNIQUE 制約ってそれぞれ一意性が別 (PK は PK 同士 UNIQUE 制約は UNIQUE 制約同士で一意性が保たれる) なので, 同じ場所テキストだとエラー出すんですよね… (実際に試したらそういう挙動になりました) ~~

**Comment by KashEight** [comment]
備考に関してめんどいことがあったのでまた設計変えちゃいました… (修正はまた後日です)

**Comment by KashEight** [comment]
ER 図更新しました
