### ISSUE TITLE
Googleアカウントの認証後に正しくリダイレクトされない

### ISSUE THREAD

**Issue by caffeine0coffee** [lc-tut/club-portal#39]
ログイン処理を試したくてfrontに作ったブランチ「test/202202」で説明する。

https://github.com/lc-tut/club-portal-frontend/blob/ae679d0be45ff40b069db790e79d0e4b47840f3a/src/components/global/Header.tsx#L45-L50
```
{/* TODO: 他にいい方法ある？ */}
<a href={"/api/auth/signin?redirect_url="+loc.pathname}>
  <Button>
    Login
  </Button>
</a>
```

こういうコードで

1. `/api/auth/signin/` にGET、Googleアカウントの認証ページ移動
2. `redirect` クエリで現在位置に戻る (`loc.pathname` が現在位置 (`/clubs` など) にあたる)

をやろうとしても `localhost:8080/*` (バックエンド側のポート) に戻ってしまい 404 Not Found となってしまった。

そこで、
https://github.com/lc-tut/club-portal/blob/2a7dc74db73aa3e29bc44b38e3b4d90b869ac6f9/router/auth/callback.go#L53-L63
の62行目を
```
ctx.Redirect(http.StatusFound, "http://localhost:8000"+redirectURL)
```
に直したところ、正しくリダイレクトされるようになった。

まだ一晩勉強しただけなので、フロントエンドでの使い方が悪いのかバックエンドのバグなのかは分からない。

**Comment by caffeine0coffee** [comment]
リバースプロキシってこういう時に使うやつなんすね〜（無知）

よろしくお願いします🙏

**Comment by KashEight** [comment]
fix: https://github.com/lc-tut/club-portal/commit/9e019d0b29d62b070e5bc4d61f94b2aea29d2b4a
