### ISSUE TITLE
コンセプトの提案

### ISSUE THREAD

**Issue by caffeine0coffee** [lc-tut/club-portal#5]
# このissueの目的

現状のサークルポータルの改善や、大学側で用意されたサークル情報のページ ( https://www.teu.ac.jp/student/circle/index.html ) との差別化を図る為に、新しいサークルポータルの目的やコンセプトを考えました。
それをここで提案・共有し、議論や意見交換を通して方向性を固めていくことがこのissueの目的です。
DB設計に影響を及ぼす思うので、それについても話していければと思っています。

# コンセプトとコードネーム

新しいサークルポータルのコンセプトとして、「知りたいサークルの情報がダイレクトに伝わるサイト」を提案します。
内容を考えていく中で、コードネームを「Direct」としてみました。

## 解決すべき課題

このコンセプトを考えるにあたり、最初に解決すべき課題の設定を行いました。

サークルを探す新入生やコロナ禍でサークル参加ができなかった新2年生(以降は両者を「探す人」と呼称します)が抱える課題として以下のものが考えられます。

- ~~サークルの情報が見つけにくい~~
- サークルへの参加方法が分からない
- 最新の情報が入手できない

このうち、1番目の項目は大学公式のサークル情報ページでも解決できると考えられます。
キャンパスごと・文体別にサークル一覧を見ることができ、検索エンジンで「東京工科大学　サークル」と検索して容易にアクセスできる為です。しかしながら、掲載された情報が古いことは大きな課題です。

また、新歓や説明会の情報を発信する各サークルの部員(以降は「発信者」と呼称します)が抱える問題としては以下のものが考えられます。

- 大学公式のサークル紹介ページを更新するのは手間がかかる
    - 大学や現状のサークルポータル管理者のLinuxClubに連絡する必要がある
    - したがって「探す人」は最新情報を入手できるとは限らない
- twitter等のSNSでイベント情報を発信するのは手間であり、学外の人にまで情報が行き届いてしまうため危険である
- twitter等のSNSによって「探す人」に情報が発信できるかどうかは、拡散を行う各々のユーザーと「探す人」との繋がりに依存する為、非合理的である

加えて、現状のサークルポータルが抱える課題としては次のものが考えられました。

- デザインが良くない
    - スタイリッシュでない
    - 「レトロさ」や「お手製感」を感じさせるデザインで、「信頼感」を演出できていない
- 使い方が直感的に分からない
- 情報がひと目で分からない
- すなわち現状のサークルポータルが「使いにくいもの・使いたくならないもの」である

## 「Direct」の目的

「Direct」が上記の課題を解決する為には、

1. 「発信者」の情報更新を容易にする
2. リアルタイムなイベント情報を容易に発信できるようにする
3. デザインを改善させ、UXを向上させる

の3つが必要であると考えられます。

1\.に関しては、学務課やLinuxClubへの連絡なしに情報更新を行えることが重要であるため、専用の編集用ページを実装する必要があります。これは大学公式ページとの差別化を行うために特に重要なことであると認識しています。

2\.に関しては、活動予定にイベント情報などの不定期な予定を追加することや、お知らせページを実装することが必要になります。「発信者」が自由に追加できるイベント用スペースを実装することも考えています。恐らくここが既存のDB設計に影響します。

3\.に関しては、デザイン・レイアウト・ナビゲーションなどを熟考し実装する必要があります。学務課へのヒアリングも予定しています。

これにより、

1. 「発信者」の情報を最新のものにする
2. 「探す人」のイベント参加やサークル加入を容易にする
3. 「探す人」の情報探索を容易にする

の3つを達成することが「Direct」の目的です。
これをもとにコンセプトを「知りたいサークルの情報がダイレクトに伝わるサイト」としました。

## ターゲットと要件

Webサイトのデザインを行うためには、ターゲットを設定し、ユーザーシナリオの方向性を決める必要があります。
もちろん、今回のターゲットは東京工科大学生です。

- 男女ともにいる
- 生活パターン
    - 勉強, バイト, 遊びなど
- 好むメディア
    - twitter, InstagramなどのSNS
    - youtubeなどの動画共有サイト
    - 主にスマートフォンを使用する
- スマートフォンアプリの使用には慣れている

アンケートなどの妥当な根拠はありませんが、このような特徴を仮定すると

- 手軽で直感的に使える
    - 上で挙げたメディアとの類似性があるとユーザーの「慣れ」が促進される
- スマートフォンでも操作がしやすい
- マテリアルデザインのようなモダンで簡潔な外観

このような要件が必要であると考えました。

また、ターゲットはサークル活動に対する意識について大きく次のように分類できます

1. ある特定のサークルに目星をつけていて、そこの情報を知りたい
2. サークル活動に興味がある
3. (サークル活動にあまり興味がない)
4. ~~サークル活動に興味がない~~

このうち、サークルポータルを訪問するのは主に1.と2.が多数であると仮定し、それぞれのユーザーシナリオを考えました。

|  | 目的 | サイト内で行うこと | 目的達成 |
| ------  | --- | --------        |--------|
| 1.    | 特定のサークルの情報を知りたい     | 検索欄から探す | 目的のサークルのページに到達する |
| 2.    | どんなサークルがあるのか知りたい | キャンパスや文or体の条件で探す | 興味のあるサークルを発見する |

したがって、ユーザーがこのような目的を達成できるような視線誘導・ナビゲーションが必要となります。

## 新たに必要となるバックエンドの要件

私はバックエンド何も分かりませんが、必要そうなことをここにまとめます。

- 「発信者」が掲載内容を編集できるシステム
    - 認証も必要？
- サイト全体で共有する「お知らせ」ページに必要なDB
- 各サークルのページ内で作成される「イベント告知」用のDB
    - イベントは1サークルあたり可変個数(>=0)ある

**Comment by KashEight** [comment]
>「発信者」が掲載内容を編集できるシステム

これは仕様をまだ完全に公開し切れてない自分が悪くて, [example/config.toml](https://github.com/lc-tut/club-portal/blob/master/examples/config.toml) の以下の部分が『発信者』でページを編集する権限を持つメールアカウントとなります. 今のところサークルの "公式" メールアドレスのみがここに入る予定です. (セキュリティ対策のため)

https://github.com/lc-tut/club-portal/blob/c13c812bf7be97f9477947d06f58bf604bdf37a6/examples/config.toml#L21-L23

> サイト全体で共有する「お知らせ」ページに必要なDB

これは, `ClubPage` テーブルと同じ要領で `AnnouncementPage` (長いかな？) テーブルみたいのを作って設計すればうまく行きそうですね.

> 各サークルのページ内で作成される「イベント告知」用のDB

これは既存の `ClubPage` に `ClubEvent` テーブルの One-to-Many の関連付けを行うことで解決しそうですね.
『お知らせ』ページにも同じリアルタイムでイベント情報を乗っけることも前提に色々考えたいです.

**Comment by KashEight** [comment]
仕様あたりは kibela で公開する予定です (やれてなくてごめんなさい)
